name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release
        cd IronBlock.Tests
        dotnet test
    - name: Publish
      run: |
        ! dotnet nuget push **/IronBlock.3.*.nupkg --source 'https://api.nuget.org/v3/index.json' -k ${{ secrets.nuget }}
      if: github.ref == 'refs/heads/master'